[project]
name = "fastapi-example"
version = "0.1.0"
description = "A very simple FastAPI application"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.115.12",
    "uvicorn>=0.34.0",
]
